version: '2.1'

services:

  # Elasticsearch, Logstash, Kibana
  elk:
    image: sebp/elk:563
    ports:
    - "9200:9200"   # elasticsearch
    - "5601:5601"   # kibana
    - "5044:5044"   # logstash tcp
    - "5046:5046"   # logstash beats
    volumes:
    - "./logstash:/etc/logstash/conf.d"

